version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
    restart: always